WebAppClient/Models/Disease.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppClient.Models
{
    public class Disease
    {
        public int DiseaseId { get; set; }

        [Required]
        [MaxLength(200)]
        public string Name { get; set; }

        public List<Symptom> DiseasesSymptoms { get; set; }
    }
}

WebAppClient/Models/ErrorViewModel.cs
using System;

namespace WebAppClient.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebAppClient/Models/Symptom.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppClient.Models
{
    public class Symptom
    {
        public int SymptomId { get; set; }
        [Required]
        [MaxLength(200)]
        public string Name { get; set; }

        public bool IsSelected { get; set; } = false;

        public List<Disease> SymptomsDiseases { get; set; }
    }
}

WebAppClient/ViewModels/DiagnoseViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppClient.Models;

namespace WebAppClient.ViewModels
{
    public class DiagnoseViewModel
    {
        public List<Symptom> AllSymptoms { get; set; }
        public List<Disease> DiseasesBySymptoms { get; set; }
    }
}

WebAppClient/ViewModels/InformationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppClient.Models;

namespace WebAppClient.ViewModels
{
    public class InformationViewModel
    {
        public int SymptomCount { get; set; }
        public List<Symptom> TopSymptoms { get; set; }
        public List<Disease> TopDiseases { get; set; }
    }
}

WebAppClient/Controllers/DiagnoseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebAppClient.Models;
using WebAppClient.Services.Interfaces;
using WebAppClient.ViewModels;

namespace WebAppClient.Controllers
{
    public class DiagnoseController : Controller
    {
        private readonly ISymptomService _symptomService;
        private readonly IDiseaseService _diseaseService;

        public DiagnoseController(ISymptomService symptomService, IDiseaseService diseaseService)
        {
            _symptomService = symptomService;
            _diseaseService = diseaseService;
        }

        // GET: Diagnose
        public async Task<ActionResult> Index()
        {
            var vm = new DiagnoseViewModel();
            vm.AllSymptoms = await _symptomService.GetAllSymptomsAsync();
            return View(vm);
        }

        // POST: Diagnose/Diseases
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Diseases(DiagnoseViewModel vm)
        {
            List<Symptom> symptoms = vm.AllSymptoms.Where(x => x.IsSelected).ToList();
            vm.DiseasesBySymptoms = await _diseaseService.GetDiseasesBySymptomsAsync(symptoms);
            return View(vm);
        }
    }
}

WebAppClient/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebAppClient.Models;
using WebAppClient.Services.Interfaces;

namespace WebAppClient.Controllers
{
    public class HomeController : Controller
    {
        private readonly IDiseaseService _diseaseService;

        public HomeController(IDiseaseService diseaseService)
        {
            _diseaseService = diseaseService;
        }

        // GET: Home/Index
        public IActionResult Index()
        {
            return View();
        }

        // GET: Home/Upload
        public ActionResult Upload()
        {
            return View();
        }

        // POST: Home/Upload
        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile file)
        {
            var filePath = Path.GetTempFileName();

            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }

            var lines = await System.IO.File.ReadAllLinesAsync(filePath);
            var list = new List<string>(lines);
            await _diseaseService.RedoDatabase(list);

            return RedirectToAction("Index", "Information");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebAppClient/Controllers/InformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebAppClient.Services.Interfaces;
using WebAppClient.ViewModels;

namespace WebAppClient.Controllers
{
    public class InformationController : Controller
    {
        private readonly ISymptomService _symptomService;
        private readonly IDiseaseService _diseaseService;

        public InformationController(ISymptomService symptomService, IDiseaseService diseaseService)
        {
            _symptomService = symptomService;
            _diseaseService = diseaseService;
        }

        // GET: Information
        public async Task<ActionResult> Index()
        {
            var vm = new InformationViewModel();
            vm.SymptomCount = await _symptomService.GetUniqueSymptomNumberAsync();
            vm.TopSymptoms = await _symptomService.GetTopSymptomsAsync();
            vm.TopDiseases = await _diseaseService.GetTopDiseasesAsync();
            return View(vm);
        }
    }
}

WebAppClient/Views/Diagnose/Diseases.cshtml
@model WebAppClient.ViewModels.DiagnoseViewModel

@{
    ViewData["Title"] = "Diseases";
}

<h2>Diseases matching selected symptoms</h2>
@if (Model.DiseasesBySymptoms.Count == 0)
{
    <strong>No Diseases match these symptoms.</strong>

}
<ul>
    @foreach (var dis in Model.DiseasesBySymptoms)
    {
        <li>
            @Html.DisplayFor(x => dis.Name)
        </li>
    }
</ul>
<br />

<h4>Symptoms you selected: </h4>
<ul>
    @foreach (var sym in Model.AllSymptoms.Where(x => x.IsSelected == true))
    {
        <li>
            @Html.DisplayFor(x => sym.Name)
        </li>
    }
</ul>

<a asp-action="Index">Back</a>

WebAppClient/Views/Diagnose/Index.cshtml
@using System.Linq
@model WebAppClient.ViewModels.DiagnoseViewModel
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<div>
    <form asp-action="Diseases">
        <strong>All symptoms: </strong>
        @for (int i = 0; i < Model.AllSymptoms.Count(); i++)
        {
            <input type="hidden" asp-for="AllSymptoms[i].SymptomId" />
            <input type="hidden" asp-for="AllSymptoms[i].Name" />
            <div class="checkbox">
                <label>
                    <input asp-for="AllSymptoms[i].IsSelected" type="checkbox" />
                    @Html.DisplayFor(x => Model.AllSymptoms[i].Name)
                </label>
            </div>
        }
        <input type="submit" value="Search diseases" class="btn btn-default" />
    </form>
</div>

WebAppClient/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Welcome to hospital client side</h2>

WebAppClient/Views/Home/Upload.cshtml
@{
    ViewData["Title"] = "Upload";
}

<h3>Insert file to use different database</h3>

<div>
    <form asp-action="Upload" method="post" enctype="multipart/form-data">
        <h4>Add file</h4>

        <div class="form-group">
            <input class="form-control" type="file" name="file" />
            @*<input asp-for="database" class="form-control" type="text" />*@
        </div>
        <input type="submit" value="Make new database" class="btn btn-default" />
    </form>
</div>

WebAppClient/Views/Information/Index.cshtml
@model WebAppClient.ViewModels.InformationViewModel
@{
    ViewData["Title"] = "Index";
}

<h2>Information</h2>

<div>
    <strong>Top 3 diseases: </strong>
    <ul>
        @foreach (var dis in Model.TopDiseases)
        {
            <li>
                @Html.DisplayFor(x => dis.Name)
            </li>
        }
    </ul>
</div>

<div>
    <strong style="display: inline">Number of unique symptoms: </strong> @Html.DisplayFor(model => model.SymptomCount)
</div>
<br />

<div>
    <strong>Top 3 symptoms: </strong>
    <ul>
        @foreach (var sym in Model.TopSymptoms)
        {
            <li>
                @Html.DisplayFor(x => sym.Name)
            </li>
        }
    </ul>
</div>

WebAppClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppClient</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WebAppClient</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Upload">Upload csv</a></li>
                    <li><a asp-area="" asp-controller="Information" asp-action="Index">Information (ex1)</a></li>
                    <li><a asp-area="" asp-controller="Diagnose" asp-action="Index">Diagnose (ex2)</a></li>

                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - WebAppClient</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>